#!/usr/bin/env python3
"""Write docs/toros-product-data-gaps.md from the catalogue itself.

Generated rather than hand-written so it cannot drift from the records. Rerun
it after editing data/products.ts or lib/product-media.ts.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs/toros-product-data-gaps.md"

BLADE_FIELDS = [
    ("steel", "blade steel"), ("bladeLength", "blade length"),
    ("__thickness", "blade stock thickness"), ("__profile", "blade shape / profile"),
    ("__grind", "edge / grind"), ("__finish", "blade finish or coating"),
    ("__hardness", "heat treatment / hardness"),
]
HANDLE_FIELDS = [
    ("handleMaterial", "handle material"), ("__handleLength", "handle length"),
    ("__tang", "construction / tang type"), ("__fittings", "liners, pins, bolsters, spacers"),
    ("__grip", "surface finish and grip"),
]


def parse_products(src: str) -> list[dict]:
    """A deliberately small reader for the one literal in data/products.ts."""
    out = []
    for block in src.split("withDefaults({")[1:]:
        rec = {}
        for key in ["slug", "name", "category", "steel", "handleMaterial",
                    "bladeLength", "totalLength", "weight", "sheath", "madeIn"]:
            m = re.search(rf'\n    {key}:\s*\n?\s*"((?:[^"\\]|\\.)*)"', block)
            if m:
                rec[key] = m.group(1)
        m = re.search(r"\n    customAvailable:\s*(true|false)", block)
        rec["customAvailable"] = m.group(1) == "true" if m else False
        if "slug" in rec:
            out.append(rec)
    return out


def missing(rec: dict, fields) -> list[str]:
    out = []
    for key, label in fields:
        value = rec.get(key)
        if key.startswith("__"):
            out.append(label)          # no such field exists on any product
        elif not value or value.strip().upper() == "N/A" or value.startswith("Varies"):
            out.append(label)
    return out


def main() -> None:
    products = parse_products((ROOT / "data/products.ts").read_text())
    media = (ROOT / "lib/product-media.ts").read_text()
    split_slugs = {
        m.group(1)
        for m in re.finditer(r'"([a-z0-9-]+)": \{(?:(?!\n  \},)[\s\S])*?kind: "split"', media)
    }
    relief_slugs = set(re.findall(r'relief: \{ dir: "/images/spin/([a-z0-9-]+)"', media))

    lines = [
        "# Product data and media gaps",
        "",
        "Generated by `scripts/build-data-gaps.py` from `data/products.ts` and",
        "`lib/product-media.ts`. Rerun it after editing either; do not hand-edit this",
        "file.",
        "",
        "Missing values are **omitted** from the site, never shown as \"N/A\" or filled",
        "with a guess. This document is the list of what someone with the knives in",
        "hand would need to write down.",
        "",
        "## Media, per product",
        "",
        "Every product is in `single` mode: it has exactly one photograph. No product",
        "has a photographed turntable, a second real angle, or a measured 3D model, so",
        "nothing in the site is labelled 360.",
        "",
        "| Product | Viewer mode | Movement it has | Anatomy | What would upgrade it |",
        "|---|---|---|---|---|",
    ]

    for p in products:
        slug = p["slug"]
        relief = slug in relief_slugs
        movement = "derived 90° sweep" if relief else "flat tilt only"
        anat = "separates" if slug in split_slugs else "**whole photo only**"
        upgrade = ("36-frame turntable" if relief
                   else "cutout + 36-frame turntable")
        lines.append(f"| {p.get('name', slug)} | single | {movement} | {anat} | {upgrade} |")

    lines += [
        "",
        "### Why nine products do not separate",
        "",
        "Anatomy clips one cutout along a measured line. Nine photographs cannot be",
        "cut honestly:",
        "",
        "- **Knife resting on its sheath** — a cut across the knife tears the sheath in",
        "  half. `bos-deri`, `bos-stag-golden-horn`, `gur-mizrak`, `gur-tombik`,",
        "  `gur-tuva`, `misty-rebar-shank`.",
        "- **Three knives in one frame** — there is no single subject to separate.",
        "  `sakra-bear-claw-neck-knives`, `toros-jellybean`.",
        "- **No usable cutout** — background removal loses the handle.",
        "  `toros-ram-horn`.",
        "",
        "All nine are fixed by one photograph each: the knife alone, out of its sheath,",
        "on a background it does not share a colour with.",
        "",
        "## Blade fields",
        "",
        "| Product | Missing |",
        "|---|---|",
    ]
    for p in products:
        gaps = missing(p, BLADE_FIELDS)
        lines.append(f"| {p.get('name', p['slug'])} | {', '.join(gaps) if gaps else '—'} |")

    lines += ["", "## Handle fields", "", "| Product | Missing |", "|---|---|"]
    for p in products:
        gaps = missing(p, HANDLE_FIELDS)
        lines.append(f"| {p.get('name', p['slug'])} | {', '.join(gaps) if gaps else '—'} |")

    lines += ["", "## Carry and customization", "", "| Product | Sheath | Customization |", "|---|---|---|"]
    for p in products:
        sheath = p.get("sheath") or "**not recorded**"
        custom = "offered" if p.get("customAvailable") else "**not recorded**"
        lines.append(f"| {p.get('name', p['slug'])} | {sheath} | {custom} |")

    lines += [
        "",
        "## Fields no product has",
        "",
        "These appear on every comparable maker's product page and on none of ours, so",
        "they are absent from the schema rather than empty in it. Adding any one of",
        "them means adding an optional typed field and filling it for the products it",
        "is known for — not adding it everywhere with a guess:",
        "",
        "- blade stock thickness, shape/profile, grind, finish or coating",
        "- heat treatment and hardness",
        "- handle length and thickness, tang type, liners, pins, bolsters, spacers",
        "- what customization actually changes, and what it costs",
        "",
        "## The one open contradiction",
        "",
        "`gur-tuva`'s record says **Deer Antler**. The photograph in",
        "`public/images/products/gur-tuva/main.jpg` shows a dark wooden handle, and the",
        "blade is etched `BOS / GUR TUVA`, so the photograph is of a GUR Tuva. The",
        "store's own listing thumbnail for GUR Tuva shows an antler-handled knife with",
        "a hammer-textured blade — a different unit.",
        "",
        "So either the model is offered in more than one handle material, or the",
        "photograph and the record describe different units. Neither has been changed:",
        "a photograph is not authority to overwrite a written record, and a record is",
        "not authority to discard a photograph. The maker can settle it in one line.",
        "",
    ]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(products)} products, "
          f"{len(split_slugs)} separable, {len(relief_slugs)} with a derived sweep")


if __name__ == "__main__":
    main()
