#!/usr/bin/env python3
"""Write docs/nature-hero-asset-manifest.md from the plates on disk.

Generated so the file cannot drift from what is actually shipped. Rerun after
scripts/build-photo-scenes.py.
"""
import json, os
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SC = ROOT / "public/images/hero/scenes"
KN = ROOT / "public/images/hero/knives"
OUT = ROOT / "docs/nature-hero-asset-manifest.md"

ORDER = ["toros-jellybean", "bos-stag-golden-horn", "sakra-bear-claw-neck-knives",
         "misty-stubby-giraffe", "misty-rebar-shank", "gur-tuva", "gur-tombik"]
LAYERS = ["sky", "far", "mid", "surface", "fore"]

TIER = {
    "bos-stag-golden-horn": ("Ready", "Sharpest source of the seven; the cutout holds at hero size."),
    "gur-tombik": ("Ready", "Clean cutout, strong grain in the surface it was shot on."),
    "gur-tuva": ("Ready", "Clean cutout. The record's handle material is disputed — see docs/toros-product-data-gaps.md."),
    "misty-stubby-giraffe": ("Ready", "Clean cutout, the most figured surface in the set."),
    "misty-rebar-shank": ("Ready", "Clean cutout; the twisted handle survives masking well."),
    "sakra-bear-claw-neck-knives": ("Temporary", "Source photograph shows five colourways together; one knife was isolated. Needs a single-subject shot."),
    "toros-jellybean": ("Temporary", "Smallest source region of the seven (136x433 before a 2x resample). Visibly soft above about 320px wide."),
}

def kb(p): return f"{p.stat().st_size / 1024:.0f} KB"

rows, total = [], 0
for slug in ORDER:
    for layer in LAYERS:
        p = SC / f"{slug}-{layer}.webp"
        if not p.exists():
            rows.append((slug, layer, "MISSING", "", ""))
            continue
        im = Image.open(p)
        total += p.stat().st_size
        rows.append((slug, layer, f"{im.width}x{im.height}", kb(p), "generated"))

lines = [
    "# Nature hero asset manifest",
    "",
    "Generated by `scripts/build-nature-manifest.py`. Do not hand-edit.",
    "",
    "## How these were made",
    "",
    "Every plate is built from the knife's own product photograph by",
    "`scripts/build-photo-scenes.py`. The makers shot each knife outdoors on a",
    "real weathered stump in real light; the largest rectangle of that",
    "photograph containing no knife at all is taken whole, extended, defocused",
    "and graded into the five layers below.",
    "",
    "Nothing is generated by a model. No landscape is invented. The knife is",
    "not removed by inpainting — a product-free region is used instead — so no",
    "ghost of it can survive into a background layer.",
    "",
    "## Layers, per knife",
    "",
    "| Knife | Layer | Size | Weight | Source |",
    "|---|---|---|---|---|",
]
for slug, layer, size, weight, src in rows:
    lines.append(f"| {slug} | {layer} | {size} | {weight} | {src} |")

lines += [
    "",
    f"**Total plate weight: {total / 1024 / 1024:.2f} MB across {len(rows)} files.**",
    "Only the active scene's five layers load eagerly; the rest are lazy.",
    "",
    "## Product cutouts",
    "",
    "The one photographed thing in each frame. Masked only — no pixel of any",
    "knife is generated, sharpened into false texture, or altered.",
    "",
    "| Knife | Cutout | Weight | Status | Note |",
    "|---|---|---|---|---|",
]
for slug in ORDER:
    p = KN / f"{slug}.png"
    im = Image.open(p)
    tier, note = TIER[slug]
    lines.append(f"| {slug} | {im.width}x{im.height} | {kb(p)} | **{tier}** | {note} |")

lines += [
    "",
    "## Status tiers",
    "",
    "1. **Ready with the current photograph** — five knives. The cutout is",
    "   clean at hero size and the scene built from its photograph holds up.",
    "2. **Acceptable temporary demonstration** — two knives, both flagged",
    "   above. They show the direction but should not be considered finished.",
    "3. **Should be replaced with higher-resolution originals** — all seven,",
    "   eventually. See the list below.",
    "",
    "## What is still needed from the makers",
    "",
    "In priority order. None of it blocks the current build; all of it would",
    "materially improve it.",
    "",
    "1. **Camera originals of the seven hero photographs.** Everything on the",
    "   site was cropped from phone screenshots of the old storefront. The",
    "   originals would sharpen both the knife and the environment built from",
    "   it, at no design cost.",
    "2. **A single-subject shot of Sakra Bear Claw and of Toros Jellybean.**",
    "   Both current sources show several knives in one frame.",
    "3. **Wider frames of the stumps, with no knife in them.** Half of each",
    "   plate is currently an upscale of a small clean rectangle. A few wide",
    "   shots of the same surfaces — empty — would replace that entirely.",
    "4. **One genuinely different location each.** The seven scenes are",
    "   separated by grade rather than geography because the source",
    "   photographs share one grey afternoon on one stump. A creek, a stone",
    "   ledge, a fire ring and a grass field would make them different places",
    "   rather than different times of day.",
    "5. **The workshop photograph**, at full resolution, as a file rather than",
    "   pasted into a chat. It belongs on About, not in a hero.",
    "",
]
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT.relative_to(ROOT)} ({total/1024/1024:.2f} MB of plates)")
